### ISSUE TITLE
New versioning scheme for Redis Docker image

### ISSUE THREAD

**Issue by jochenehret** [frodenas/docker-redis#2]
Hi Ferran,

we would like to request a more explicit versioning scheme which helps us (and hopefully others) to consume the Docker Redis image. The problem is that currently there is only a tag "2.8" which does not contain the Redis patch version. Can you enhance your versioning scheme to include the patch version and also (as 4th component) the version of your Dockerfile? For example, for the current version, the tag would be "2.8.22.0". If you have to change the Dockerfile, but not the Redis version, you could go to "2.8.22.1". We'll open a pull request for Redis 2.8.23 which should then be tagged as "2.8.23.0".

Thanks for your support!

Best Regards,

  Philipp & Jochen.

**Comment by frodenas** [comment]
I added a new 2.8.23 branch. I don't see any compelling reason to add the Dockerfile version, it has never changed beside the redis version.

**Comment by jochenehret** [comment]
Hi Ferran,

thanks for the quick response! Should the Dockerfile (or the startup scripts, license etc.) change in the future, it would be great if you could mark that in the version with a 4th number.

Best Regards,

  Jochen.
